from fpdf import FPDF

pdf = FPDF(format='A5')
pdf.set_font('Arial', 'B', 12)
pdf.add_page()
pdf.rect(x=10, y=10, h=190, w=130)
pdf.rect(x=9, y=9, h=192, w=132)
pdf.image('img.png', h=15, x=20, y=14, w=100)
pdf.ln(1)
# this for margin left
pdf.cell(w=15, h=4, txt='')
# this for border
pdf.cell(h=25, w=100, txt='', border='B', ln=1)
pdf.set_text_color(0, 0, 255)
pdf.cell(txt='Cordially invites you to the program on', w=130, h=8, align='C', ln=1)
pdf.cell(w=10, h=15, txt='')
pdf.cell(h=1, w=100, txt='', border='B', ln=1, align='C')
# function name section
pdf.set_text_color(0, 0, 0)
pdf.set_fill_color(0, 77, 0)
pdf.set_font('Arial', 'B', 14)
pdf.cell(txt='FUNCTION NAME FUNCTION YEAR', w=130, h=8, align='C', ln=1)
pdf.cell(w=5, h=3, txt='')
pdf.set_font('Arial', 'B', 12)
pdf.cell(h=1, w=120, txt='', border='B', ln=1)
# date time ssection
pdf.cell(w=5, h=1, txt='', ln=1)
pdf.cell(w=10, h=5, txt='')
pdf.cell(w=100, h=4, txt='Date: 16th september 2022 Time: 02:00PM', ln=1)
pdf.cell(w=10, h=2, txt='', ln=1)
pdf.cell(w=10, h=4, txt='')
pdf.cell(w=100, h=4, txt='Venue: Conference Hall', align='C', ln=1)
pdf.cell(w=10, h=10, txt='')
pdf.cell(h=2, w=110, txt='', border='B', ln=1)
pdf.cell(w=50, h=2, txt='', ln=1)
# chief guest section
pdf.set_font('Arial', 'B', 10)
pdf.cell(w=130, h=4, txt='Chief Guest', align='C', ln=1)
pdf.cell(w=50, h=4, txt='', ln=1)
pdf.cell(w=3, h=3, txt='', ln=0)
pdf.cell(txt='Prof.Dr.A.MAHENDIRAN', w=50, h=5)
pdf.cell(w=20, h=3, txt='', ln=0)
pdf.cell(txt='Prof.Dr.G.SENTHILRAJA', w=50, h=5, ln=1)
pdf.cell(w=3, h=3, txt='', ln=0)
pdf.cell(txt='Vice-Principal', w=50, h=5)
pdf.cell(w=20, h=3, txt='', ln=0)
pdf.cell(txt='HOD/Department of Tamil', w=50, h=5, ln=1)
pdf.cell(w=3, h=3, txt='', ln=0)
pdf.cell(txt='Thanthai Hans Rovere collage', w=50, h=5)
pdf.cell(w=20, h=3, txt='', ln=0)
pdf.cell(txt='Thanthai Hans Rovere collage', w=50, h=5, ln=1)
pdf.cell(w=3, h=3, txt='', ln=0)
pdf.cell(txt='Perambalur', w=50, h=5)
pdf.cell(w=20, h=3, txt='', ln=0)
pdf.cell(txt='perambalur', w=50, h=5, ln=1)

# chief guest section 2
pdf.cell(txt='', w=5, h=5, ln=1)
pdf.cell(txt='Dr.K.VARADHARAAJEN', h=5, w=130, align='C', ln=1)
pdf.cell(txt='Chairman                         ', h=5, w=130, align='C', ln=1)
pdf.cell(txt='     Roever Group of Institution', h=5, w=130, align='C', ln=1)
pdf.cell(txt='         Will preside over the function', h=5, w=130, align='C', ln=1)
pdf.cell(txt='', w=5, h=5, ln=1)
pdf.cell(txt='Dr.K.VARADHARAAJEN', h=5, w=130, align='C', ln=1)
pdf.cell(txt='Chairman                         ', h=5, w=130, align='C', ln=1)
pdf.cell(txt='     Roever Group of Institution', h=5, w=130, align='C', ln=1)
pdf.cell(txt='         Will preside over the function', h=5, w=130, align='C', ln=1)
pdf.cell(txt='', w=5, h=10, ln=1)
# chief guest section 3
pdf.cell(txt='Organized by', h=5, w=130, align='C', ln=1)
pdf.cell(txt='Internal Quality Assurance Cell', h=5, w=130, align='C', ln=1)
pdf.cell(txt='', w=5, h=7, ln=1)
pdf.cell(txt='', w=5, h=1, ln=1)
pdf.rect(x=11,y=172,w=50,h=15)
pdf.rect(x=80,y=172,w=50,h=15)
# chief guest section 4
pdf.set_font('Arial', 'B', 12)
pdf.cell(txt=' Dr.C.G.GUNASUNDARI', h=5, w=50, align='C', ln=0)
pdf.cell(txt='', w=20, h=3, ln=0)
pdf.cell(txt='Dr.C.G.GUNASUNDARI', h=5, w=50, align='C', ln=1)
pdf.cell(txt='  IQAC,Member,REC', h=5, w=50, ln=0)
pdf.cell(txt='', w=20, h=5, ln=0)
pdf.cell(txt='IQAC,Coordinator,REC', h=5, w=50, ln=0)
pdf.cell(txt='', h=5, w=80, align='C', ln=1)

pdf.output('abc.pdf')
